"""Build a readable, printable HTML book from the reviewed Markdown chapters."""
import pathlib, re, html, markdown
root=pathlib.Path(__file__).resolve().parents[1]
chapters=sorted((root/'book').glob('[0-9][0-9]-*.md'))
sections=[]; navigation=[]
for i,path in enumerate(chapters,1):
    source=path.read_text(encoding='utf-8')
    title=source.splitlines()[0].lstrip('# ')
    navigation.append(f'<a href="#part{i}">{html.escape(title)}</a>')
    rendered=markdown.markdown(source,extensions=['fenced_code','tables','toc'])
    flow='''<svg viewBox="0 0 940 200" role="img" aria-label="Браузер, listener, router, backend group и два nginx" style="width:100%;height:auto"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0 L8 3 L0 6" fill="#2c7196"/></marker></defs><g fill="#edf7f8" stroke="#2c7196" stroke-width="2"><rect x="10" y="70" width="140" height="60" rx="8"/><rect x="200" y="70" width="140" height="60" rx="8"/><rect x="390" y="70" width="140" height="60" rx="8"/><rect x="580" y="70" width="145" height="60" rx="8"/><rect x="780" y="20" width="150" height="60" rx="8"/><rect x="780" y="120" width="150" height="60" rx="8"/></g><g fill="none" stroke="#2c7196" stroke-width="2" marker-end="url(#arrow)"><path d="M150 100H200"/><path d="M340 100H390"/><path d="M530 100H580"/><path d="M725 100L780 50"/><path d="M725 100L780 150"/></g><g fill="#173d59" font-family="sans-serif" font-size="17" text-anchor="middle"><text x="80" y="105">Браузер</text><text x="270" y="105">Listener :80</text><text x="460" y="105">HTTP router /</text><text x="652" y="105">Backend group</text><text x="855" y="55">nginx web-a</text><text x="855" y="155">nginx web-b</text></g></svg>'''
    rendered=re.sub(r'<pre><code class="language-mermaid">.*?</code></pre>',flow,rendered,flags=re.S)
    sections.append(f'<section id="part{i}">{rendered}</section>')
page='''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Как устроен диплом системного администратора</title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#eef2f7;color:#172637;font:18px/1.75 Georgia,serif}header,main{max-width:1040px;margin:auto;padding:42px 64px;background:#fff}header{background:#143751;color:white;padding-top:68px}header h1{color:white;font:700 42px/1.18 system-ui}header p{max-width:760px}nav a{display:block;color:#163f67;text-decoration:none;margin:12px 0;font-family:system-ui}section{padding-top:32px;margin-bottom:64px}h1,h2,h3{font-family:system-ui;line-height:1.3;color:#173d59}h2{margin-top:38px}h3{margin-top:28px}pre{background:#edf2f6;border-left:4px solid #2c7196;padding:20px;overflow:auto;font:14px/1.6 Consolas,monospace}code{font-family:Consolas,monospace;font-size:.88em}table{width:100%;border-collapse:collapse;font:15px/1.5 system-ui;margin:24px 0}td,th{border:1px solid #cad4dd;padding:10px;text-align:left}th{background:#edf2f6}blockquote{border-left:4px solid #3893aa;margin:24px 0;padding:8px 24px;background:#edf7f8}a{color:#165e88}footer{font:14px system-ui;color:#547080;margin-top:40px}@media(max-width:700px){header,main{padding:24px}header h1{font-size:30px}body{font-size:17px}}@media print{header h1{color:#172637}body{background:white;font-size:11pt}header,main{padding:0;max-width:none}header{color:#172637;background:white;page-break-after:always}section{page-break-before:always}pre{white-space:pre-wrap;font-size:9pt}h2,h3{page-break-after:avoid}tr{page-break-inside:avoid}a{color:inherit}}
</style><header><p>ПРАКТИЧЕСКОЕ УЧЕБНОЕ ПОСОБИЕ</p><h1>Как устроен диплом системного администратора</h1><p>От первого HTTP-запроса до восстановления из снимка: Яндекс Облако, Terraform, Ansible, nginx, Zabbix и Elastic Stack.</p><p>Анна Смага · октябрь 2026 · реальный учебный стенд</p></header><main><h2>Оглавление</h2><nav>'''+''.join(navigation)+'</nav>'+''.join(sections)+'''<footer>Исходные главы, вопросы и команды находятся в каталоге book. Для сохранения PDF используйте печать браузера. Mermaid-схемы в этом автономном HTML представлены исходным текстом; графически они отображаются в Markdown на GitHub.</footer></main></html>'''
page=page.replace('Mermaid-схемы в этом автономном HTML представлены исходным текстом; графически они отображаются в Markdown на GitHub.','Схема запроса включена в файл как SVG и работает без подключения к Интернету.')
(root/'book/handbook.html').write_bytes(page.encode('utf-8'))
print(f'Book built: {len(chapters)} parts, {sum(len(p.read_text(encoding="utf-8").split()) for p in chapters)} words')
