[web]
diplom-web-a.ru-central1.internal
diplom-web-b.ru-central1.internal
[elastic]
diplom-elastic.ru-central1.internal
[zabbix]
diplom-zabbix.ru-central1.internal
[kibana]
diplom-kibana.ru-central1.internal
[bastion]
diplom-bastion.ru-central1.internal
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/diplom
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'